packages:
    - "src/**"
    - "dev/**"
    - "tests/**"
minimumReleaseAge: 10080
trustPolicy: "no-downgrade"
allowBuilds:
    "@swc/core": false
    esbuild: false
    sharp: false
onlyBuiltDependencies:
    - sharp
    - esbuild
    - unrs-resolver
